packages/vue-i18n-loader/README.md, packages/vue-i18n-loader/src/index.ts, packages/vue-i18n-loader/src/options.ts
=> Add option productionSourceMap for vue-i18n-loader

packages/vue-i18n-loader/package.json
=> improvement: add peerDeps for vue-i18n-loader

packages/rollup-plugin-vue-i18n/package.json
=> improvement: add peerDeps for rollup-plugin-vue-i18n

.github/workflows/test.yml, packages/unplugin-vue-i18n/package.json, packages/unplugin-vue-i18n/src/index.ts, packages/unplugin-vue-i18n/src/utils.ts, yarn.lock
ref: https://github.com/unjs/unplugin/pull/144
close #152
resolve #151
=> fix(unplugin-vue-i18n): support unplugin v0.8

packages/unplugin-vue-i18n/src/index.ts
=> fix(unplugin-vue-i18n): improve wrong virtual module implementation

packages/unplugin-vue-i18n/README.md, packages/unplugin-vue-i18n/src/index.ts, packages/unplugin-vue-i18n/src/types.ts
=> feat(unplugin-vue-i18n): support petite-vue-i18n and useVueI18nImportName option

packages/vite-plugin-vue-i18n/README.md, packages/vite-plugin-vue-i18n/build.config.ts, packages/vite-plugin-vue-i18n/package.json, packages/vite-plugin-vue-i18n/src/index.ts, yarn.lock
=> breaking(vite-plugin-vue-i18n): plugin export named default only

.github/workflows/build.yml
Following up from comment https://github.com/intlify/bundle-tools/pull/160#issuecomment-1210493313: This performs a build to ensure the correctness of every commit and pull request.
=> build: Perform build in GitHub Actions

packages/bundle-utils/src/codegen.ts, packages/bundle-utils/src/json.ts, packages/bundle-utils/src/yaml.ts, packages/bundle-utils/test/fixtures/codegen/invalid-message.json, packages/bundle-utils/test/fixtures/codegen/invalid-message.yml, packages/bundle-utils/test/generator/__snapshots__/json.test.ts.snap, packages/bundle-utils/test/generator/__snapshots__/yaml.test.ts.snap, packages/bundle-utils/test/generator/json.test.ts, packages/bundle-utils/test/generator/yaml.test.ts
related: #173, #164
closes: #53, #127
=> fix(bundle-utils): fix wrong error callbacking and error handling improvement

packages/unplugin-vue-i18n/package.json, packages/unplugin-vue-i18n/src/index.ts, yarn.lock
=> fix(unplugin-vue-i18n): improve compilation error handling

packages/vite-plugin-vue-i18n/src/check.ts, packages/vite-plugin-vue-i18n/src/index.ts
=> fix(vite-plugin-vue-i18n): support vue-i18n-bridge module detection

packages/unplugin-vue-i18n/package.json, packages/unplugin-vue-i18n/src/check.ts, packages/unplugin-vue-i18n/src/index.ts, yarn.lock
=> fix(unplugin-vue-i18n): port vue-i18n-bridge module detecting from vite-plugin-vue-i18n

packages/unplugin-vue-i18n/src/index.ts
=> fix(unplugin-vue-i18n): normalize undefined resolve

packages/unplugin-vue-i18n/package.json, packages/unplugin-vue-i18n/test/utils.ts, packages/unplugin-vue-i18n/test/webpack/bundle-import.test.ts, yarn.lock
=> feat(unplugin-vue-i18n): support rollup v3 via unplugin v1.0

packages/unplugin-vue-i18n/src/index.ts, packages/unplugin-vue-i18n/test/vite/__snapshots__/sourcemap.test.ts.snap
=> fix(unplugin-vue-i18n): generate sourcemap for ts/js

packages/unplugin-vue-i18n/README.md, packages/unplugin-vue-i18n/package.json, packages/unplugin-vue-i18n/src/index.ts, packages/unplugin-vue-i18n/test/fixtures/locales/en-GB.ts, packages/unplugin-vue-i18n/test/fixtures/locales/en-KK.mjs, packages/unplugin-vue-i18n/test/fixtures/locales/en-US.js, packages/unplugin-vue-i18n/test/utils.ts, packages/unplugin-vue-i18n/test/vite/resource-compilation.test.ts, yarn.lock
related https://github.com/nuxt-modules/i18n/pull/1576
=> fix(unplugin-vue-i18n): support js and ts resource formats

packages/unplugin-vue-i18n/package.json
=> fix: types exports for "moduleResolution": "node16"

packages/unplugin-vue-i18n/README.md
=> fix: default plugin locale path

packages/bundle-utils/src/js.ts, packages/bundle-utils/src/json.ts, packages/bundle-utils/src/yaml.ts, packages/bundle-utils/test/generator/__snapshots__/js.test.ts.snap, packages/bundle-utils/test/generator/__snapshots__/json.test.ts.snap, packages/bundle-utils/test/generator/__snapshots__/yaml.test.ts.snap, packages/bundle-utils/test/generator/js.test.ts, packages/bundle-utils/test/generator/json.test.ts, packages/bundle-utils/test/generator/yaml.test.ts
add support for facing-dev/vue-facing-decorator (vue class decorator vue3)
see issue #268
=> fix(vue-facing-decorator): useClassComponent option

packages/bundle-utils/package.json, packages/bundle-utils/src/codegen.ts, yarn.lock
ref: https://github.com/nuxt-modules/i18n/issues/2208
=> fix(unplugin-vue-i18n): support esm fully

packages/unplugin-vue-i18n/package.json, yarn.lock
=> fix(unplugin-vue-i18n): upgrade deps

packages/bundle-utils/package.json, yarn.lock
=> fix(bundle-utils): bump deps

packages/unplugin-vue-i18n/messages.d.ts
Fixes https://github.com/intlify/vue-i18n-next/issues/1119
=> Set `messages` type to the vue-i18n type instead of any

packages/unplugin-vue-i18n/package.json, yarn.lock
=> fix(unplugn-vue-i18n): support rollup v4

packages/bundle-utils/package.json, yarn.lock
=> fix(bundle-utils): upgrade escodegen

packages/bundle-utils/src/json.ts, packages/bundle-utils/src/yaml.ts, packages/unplugin-vue-i18n/test/fixtures/locale-mix-json.vue, packages/unplugin-vue-i18n/test/fixtures/locale-mix-yaml.vue, packages/unplugin-vue-i18n/test/vite/__snapshots__/custom-block.test.ts.snap, packages/unplugin-vue-i18n/test/vite/custom-block.test.ts
Fixes https://github.com/intlify/bundle-tools/issues/329
=> fix(bundle-utils,unplugin-vue-i18n): exclude locales when using mixed locales #329

packages/unplugin-vue-i18n/src/core/directive.ts
=> fix(unplugin-vue-i18n): remove directives plugin warnings on SSR build

eslint.config.mjs
=> chore: fix eslint on Windows

packages/bundle-utils/src/js.ts, packages/bundle-utils/src/json.ts, packages/bundle-utils/src/yaml.ts, packages/bundle-utils/test/generator/__snapshots__/json.test.ts.snap, packages/bundle-utils/test/generator/__snapshots__/json5.test.ts.snap
Similar to the js generator refactor, the same patterns were applied to the other generators.
=> refactor: simplify generators

.github/workflows/ci.yml, packages/bundle-utils/package.json, packages/unplugin-vue-i18n/package.json
Node v18.x will be ended of life
https://github.com/nodejs/Release?tab=readme-ov-file#nodejs-release-working-group
=> breaking: drop node v18

packages/unplugin-vue-i18n/src/core/resource.ts, packages/unplugin-vue-i18n/src/utils/plugin.ts
port from https://github.com/intlify/bundle-tools/pull/484
https://github.com/intlify/bundle-tools/issues/483
=> fix(unplugin-vue-i18n): Support for `transform.handler` in vite:json plugin
