packages/bundle-utils/package.json
packages/vite-plugin-vue-i18n/package.json

The vite plugin uses vite API and require `vue-i18n` to detect which package to use. It makes sense to add them as peerDependencies and will otherwise fail with strict package manager like yarn pnp

fix: add vite and vue-i18n as peerDependencies

---

packages/vite-plugin-vue-i18n/examples/legacy/main.ts
packages/vite-plugin-vue-i18n/package.json
packages/vite-plugin-vue-i18n/src/index.ts
packages/vite-plugin-vue-i18n/test/__snapshots__/sourcemap.test.ts.snap
packages/vite-plugin-vue-i18n/test/fixtures/yml.vue
packages/vite-plugin-vue-i18n/test/sourcemap.test.ts
packages/vite-plugin-vue-i18n/test/utils.ts

feat: support sourcemap generation

---

packages/bundle-utils/src/codegen.ts
packages/bundle-utils/src/json.ts
packages/bundle-utils/src/yaml.ts
packages/bundle-utils/test/generator/__snapshots__/json.test.ts.snap
packages/bundle-utils/test/generator/__snapshots__/yaml.test.ts.snap
packages/bundle-utils/test/generator/json.test.ts
packages/bundle-utils/test/generator/yaml.test.ts
packages/vue-i18n-loader/src/index.ts
packages/vue-i18n-loader/src/options.ts

Issue: https://github.com/intlify/bundle-tools/issues/74

Add vue-class-components support via loader option

---

packages/vite-plugin-vue-i18n/src/index.ts
packages/vite-plugin-vue-i18n/test/__snapshots__/sourcemap.test.ts.snap

In Vite's transformation hook, returning nullish value will tell Vite to bypass this tranformation, which saves the cost of handling changes and source map processing.

perf(vite-plugin): skip transformation for unmodified code

---

packages/vite-plugin-vue-i18n/src/index.ts

fixes #153 
I haven't tested this, as I currently don't have access to my computer, nor github codespaces.

fix(vite-plugin-vue-i18n): use correct id in hmr

---

packages/vite-plugin-vue-i18n/src/index.ts

NOTE:
This fix is workaround for vite3 SSR.
Ideally, We hope that this fix will not be necessary once the SSR module on the vue side supports cjs/mjs.
ref: https://github.com/vuejs/core/pull/4814

fix(vite-plugin-vue-i18n): support vite3 SSR

---

packages/bundle-utils/src/deps.ts
packages/bundle-utils/src/index.ts
packages/bundle-utils/test/deps.test.ts

BREAKING: remove `isInstalledVue2` and `isInstalledVue3`, because we want to know the VueI18n version, so that's correctly than Vue version

feat!: support getVueI18nVersion API

---

packages/unplugin-vue-i18n/package.json
packages/unplugin-vue-i18n/src/index.ts
yarn.lock

fix(unplugin-vue-i18n): resource resolving and alias resolving

---

packages/unplugin-vue-i18n/README.md

It wasn't clear how the plugin imports all the locale files. So I added some more explanation.

docs(unplugin-vue-i18n): add clarification for importing all locales

---

packages/unplugin-vue-i18n/README.md

docs(unplugin-vue-i18n): add notcie for yaml format resource

---

packages/bundle-utils/package.json
packages/bundle-utils/src/js.ts
packages/bundle-utils/test/fixtures/codegen/functions.js
packages/bundle-utils/test/generator/__snapshots__/js.test.ts.snap
packages/bundle-utils/test/generator/js.test.ts
yarn.lock

fix(bundle-utils): existing functions not being generated

---

packages/unplugin-vue-i18n/src/index.ts

For Vue SFCs defaultSFCLang setting wasn't respected and if the block didn't have lang attribute it would fall back to json, even if it could be yaml

fix: Use `defaultSFCLang` setting for src files instead of falling back to json

---

packages/unplugin-vue-i18n/README.md
packages/unplugin-vue-i18n/src/index.ts
packages/unplugin-vue-i18n/src/types.ts

fix for https://github.com/intlify/vue-i18n-next/issues/1569

feat: `ssr` option

---

packages/unplugin-vue-i18n/src/index.ts

I haven't used `vueVersion` option ever, but it showed a warning on my Shell.

Fix vueVersion warning

---

packages/unplugin-vue-i18n/README.md
packages/unplugin-vue-i18n/src/index.ts
packages/unplugin-vue-i18n/src/types.ts
packages/unplugin-vue-i18n/src/utils.ts

This option is no longer needed as unplugin-vue-i18n internally analyzes the installed modules and can automatically configure `resolve.alias`

breaking: drop `useVueI18nImportName` option

---

examples/vite/src/App.vue
examples/vite/src/Apple.vue
examples/vite/vite.config.ts
examples/webpack/src/App.vue
examples/webpack/src/Apple.vue
examples/webpack/webpack.config.js
packages/bundle-utils/src/codegen.ts
packages/bundle-utils/src/json.ts
packages/unplugin-vue-i18n/README.md
packages/unplugin-vue-i18n/src/core/options.ts
packages/unplugin-vue-i18n/src/core/resource.ts
packages/unplugin-vue-i18n/src/types.ts

My organization has been using Vue i18n for over 6 years now and it has been invaluable to the project. We recently upgraded to Vue 3 and ran into an issue with the latest version if i18n and it's newest plugins.
Due to the size of our application we've had a custom loader that runs before the Vue i18n plugin in Webpack. This allows us at build time to fetch the translations and then replace the `<i18n>` blocks with the correct format.
Due to the size of our application, we can't feasibly put all the translations into our components during development so we create the slugs and then the translations are entered into our CMS by our content team. We _could_ put translations in json files in the repo - but then it requires content folks to edit via JSON files and know how to use git etc. …

feat(unplugin-vue-i18n): allow for a custom i18n block transform hook

---

packages/unplugin-vue-i18n/src/core/directive.ts

This PR includes the following changes in the `directives` plugin:
- exclude analyze identifiers when vue files using any of the following languages: `pug`, `jsx` and `tsx` (we cannot parse those languages with `@typescript-eslint/typescript-estree`)
- adds a new `excludeLangs` array containing previous languages to allow add more when required
- small refactor for perfomance
This PR doesn't fix anything about `v-t` logic in the `directives` plugin: `v-t` cannot be used (ignored/error?)
resolves #402

fix(unplugin-vue-i18n): don't analyze identifiers in vue files when using `pug/jsx/tsx` languages

---

packages/bundle-utils/package.json
packages/bundle-utils/tsconfig.json
packages/unplugin-vue-i18n/build.config.ts
packages/unplugin-vue-i18n/package.json
packages/unplugin-vue-i18n/tsconfig.json
pnpm-lock.yaml

This PR moves `@intlify/bundle-utils` and `@intlify/unplugin-vue-i18n` to ESM first (right now CJS) fixing packages exports in both packages.
<details>
<summary>Without this PR</summary>
_[@intlify/bundle-utils](https://arethetypeswrong.github.io/?p=%40intlify%2Fvite-plugin-vue-i18n%407.0.0)_
_[@intlify/unplugin-vue-i18n](https://arethetypeswrong.github.io/?p=%40intlify%2Funplugin-vue-i18n%405.3.1)_
</details>
<details>
<summary>With this PR</summary>
_@intlify/bundle-utils_
_@intlify/unplugin-vue-i18n_
</details>

feat!: move packages to ESM first

---

packages/unplugin-vue-i18n/src/core/directive.ts

fix(unplugin-vue-i18n): check for vue compiler in directive transform hook

---

packages/unplugin-vue-i18n/src/core/directive.ts

This may resolve sourcemap issues, credits to @userquin

fix: only return transform for vue files

---

packages/unplugin-vue-i18n/package.json
pnpm-lock.yaml

Updated [@intlify/vue-i18n-extensions to v8.0.0](https://github.com/intlify/vue-i18n-extensions/releases/tag/v8.0.0) to resolve unmet peer dependencies with vue-i18n@11.0.1.
- https://github.com/intlify/bundle-tools/issues/431

chore(deps): update @intlify/vue-i18n-extensions to v8.0.0

---

packages/unplugin-vue-i18n/src/core/options.ts
packages/unplugin-vue-i18n/src/core/resource.ts

This refactor mostly changes the way options are passed around in the resource plugin, and preserves the original option names to make it easier to keep track of where the values come from.

refactor: simplify resource logic

---

.github/workflows/test.yml
eslint.config.mjs
package.json
packages/bundle-utils/package.json
packages/unplugin-vue-i18n/package.json
pnpm-lock.yaml

fix(bundle-tools): pinned intlify pacakges

---

.github/workflows/ci.yml
e2e/helper.ts
e2e/vite.spec.ts
package.json
pnpm-lock.yaml
scripts/playwright.ts
scripts/vitest.setup.ts

This is the update path for `playwright`, also removes Playwright caching from the workflow as this is (I believe) recommended by their docs and consistent with the other i18n repository workflows.

chore(deps): replace `playwright` with `playwright-core`

---

packages/bundle-utils/src/js.ts
packages/bundle-utils/test/generator/__snapshots__/js.test.ts.snap

This refactor removes and reuses repeated patterns in the generate function, some aspects I still don't fully understand (for example the function of `pathStack`). But this refactor helped me see which logic is essential per node type.
The snapshots have been updated since this also removes the trailing comma from the last item in arrays, in the same way we already did for last property/value in objects.

refactor: simplify js generate

---

packages/unplugin-vue-i18n/src/core/resource.ts
packages/unplugin-vue-i18n/src/utils/plugin.ts

In vite 6.3, the handling of plugin hooks has been changed from transform to transform.handler internally.
Currently, vite is minimizing the impact on end users through a patch, but in vite 7, the patch for transform will be removed.
- #483
Rollup used internally in Vite will be replaced by Rolldown in the future. Rolldown plans to provide JSON transform plugin natively, but the current workaround that hijacks the unplugin-vue-i18n Vite JSON plugin cannot be used.
Regarding this issue, the Rolldown team and Vite team are currently discussing a workaround mechanism at the following URL. 
https://github.com/vitejs/rolldown-vite/issues/120

fix(unpluing-vue-i18n): Support for `transform.handler` in vite:json plugin

---

packages/unplugin-vue-i18n/src/core/resource.ts
packages/unplugin-vue-i18n/src/utils/plugin.ts

Reverts intlify/bundle-tools#485

Revert "fix(unplugin-vue-i18n): Support for `transform.handler` in vite:json plugin"

---

packages/unplugin-vue-i18n/src/core/resource.ts

fix(unplugin-vue-i18n): vite json plugin override compatibility

---

packages/bundle-utils/src/js.ts
packages/bundle-utils/src/ts.ts

This extracts the default options used in the js and ts generators to a constant object, to make the code a bit easier to read.

refactor: extract default options to constant object
